import './globals.css'
import { Inter } from 'next/font/google'
import { Kalam } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] })
const kalam = Kalam({subsets: ['latin'],
weight:["400"],
variable: '--font-kalam',});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kalam.className}>{children}</body>
    </html>
  )
}
